language: php

matrix:
  include:
    - sudo: required
      services:
        - docker
      env:
        - RELEASE=trusty
    - sudo: required
      env:
        - RELEASE=precise

env:
  global:
    - VERSION=5.5.30
    - ALIAS=5.5

install:
  - cp $HOME/.php-build/share/php-build/default_configure_options $HOME
  - pushd $HOME/.php-build
  - git checkout master && git reset --hard HEAD && git pull origin master
  - mv $HOME/default_configure_options $HOME/.php-build/share/php-build/default_configure_options
  - popd
  - if [ $VERSION = 'master' ]; then ALIAS='nightly'; fi
  - sed -i -e 's/--without-pear/--with-pear/' ~/.php-build/share/php-build/default_configure_options

script:
  - pushd $HOME/.php-build/bin
  - env PHP_VERSION=$VERSION ./php-build -i development $VERSION ~/.phpenv/versions/$ALIAS || cat /tmp/php-build.$VERSION.*.log
  - pushd $HOME/.phpenv/versions/$ALIAS
  - ln -sfv sbin/php-fpm bin/php-fpm
  - curl -s -o bin/composer http://getcomposer.org/composer.phar
  - curl -s -o bin/phpunit https://phar.phpunit.de/phpunit.phar
  - chmod +x bin/composer bin/phpunit
  - popd; popd
  - cp $HOME/.phpenv/versions/5.6/etc/conf.d/travis.ini $HOME/.phpenv/versions/$ALIAS/etc/conf.d/travis.ini || true
  - phpenv global $ALIAS
  - composer self-update
  - export OS_NAME=$(lsb_release -is | tr "A-Z" "a-z" || echo "osx")
  - export RELEASE=$(lsb_release -rs 2>/dev/null || sw_vers -productVersion | sed 's/^\([0-9][0-9]*.[0-9][0-9]*\).*/\1/')
  - export TARGET_DIR=$HOME/archive/binaries/$OS_NAME/${RELEASE}/$(uname -m)
  - mkdir -p $TARGET_DIR
  - tar cjf $TARGET_DIR/php-$ALIAS.tar.bz2 --directory=$HOME/.phpenv/versions $ALIAS
  - ls -lh $TARGET_DIR/php-$ALIAS.tar.bz2

deploy:
  provider: s3
  access_key_id: $ARTIFACTS_KEY
  secret_access_key: $ARTIFACTS_SECRET
  bucket: $ARTIFACTS_BUCKET
  local_dir: $HOME/archive
  on:
    branch:
      - default
      - version
  acl: public_read
