language: php

sudo: false

env:
  global:
    - VERSION=5.6.12
    - ALIAS=$VERSION

install:
  - if [ $VERSION = 'master' ]; then ALIAS='nightly'; fi
  - if [ $VERSION = 'master' ]; then sed -i -e '/xdebug/d' ~/.php-build/share/php-build/definitions/master; fi
  - if [ $VERSION = 'master' ]; then sed -i -e 's/--without-pear/--with-pear/' ~/.php-build/share/php-build/default_configure_options; fi

script:
  - pushd $HOME/.php-build
  - git checkout master && git reset --hard HEAD && git pull origin master
  - pushd $HOME/.php-build/bin
  - env PHP_VERSION=$VERSION ./php-build -i development $VERSION ~/.phpenv/versions/$ALIAS || cat /tmp/php-build.$VERSION.*.log
  - pushd $HOME/.phpenv/versions/$ALIAS
  - ln -s sbin/php-fpm bin/php-fpm
  - curl -s -o bin/composer http://getcomposer.org/composer.phar
  - curl -s -o bin/phpunit https://phar.phpunit.de/phpunit.phar
  - chmod +x bin/composer bin/phpunit
  - popd; popd; popd
  - cp $HOME/.phpenv/versions/5.6/etc/conf.d/travis.ini $HOME/.phpenv/versions/$ALIAS/etc/conf.d/travis.ini
  - phpenv global $ALIAS
  - composer self-update
  - mkdir $HOME/archive
  - tar cjf $HOME/archive/php-$ALIAS-archive.tar.bz2 --directory=$HOME/.phpenv/versions $ALIAS
  - ls -lh $HOME/archive/php-$ALIAS-archive.tar.bz2

deploy:
  provider: s3
  access_key_id: $ARTIFACTS_KEY
  secret_access_key: $ARTIFACTS_SECRET
  bucket: $ARTIFACTS_BUCKET
  local_dir: $HOME/archive
  on:
    branch:
      - default
      - version
