language: c

sudo: false

install:
  - git clone --depth=1 git@github.com:php/php-src.git
  - pushd php-src
  - ./buildconf -f
  - './configure --prefix=$HOME/.phpenv/versions/7 && make && make install'
  - popd

script:
  - pushd $HOME/.phpenv/versions/7
  - curl -s -o bin/composer http://getcomposer.org/composer.phar
  - curl -s -o bin/phpunit https://phar.phpunit.de/phpunit.phar
  - chmod +x bin/composer bin/phpunit
  - popd
  - mkdir $HOME/archive
  - tar cjf $HOME/archive/php-7-archive.tar.bz2 --directory=$HOME/.phpenv/versions 7
  - ls -lh $HOME/archive/php-7-archive.tar.bz2

deploy:
  provider: s3
  access_key_id: $ARTIFACTS_KEY
  secret_access_key: $ARTIFACTS_SECRET
  bucket: $ARTIFACTS_BUCKET
  local_dir: $HOME/archive