language: c

sudo: false

install:
  - git clone --depth=1 git@github.com:php/php-src.git
  - pushd php-src
  - ./buildconf -f
  - './configure --prefix=$HOME/.phpenv/versions/7 && make && make install'

script:
  - tar cjf $HOME/php-7-archive.tar.bz2 $HOME/.phpenv/versions/7
  - ls -lh $HOME/php-7-archive.tar.bz2

after_success:
  - artifacts upload --target-path "."
