language: php

sudo: false
env:
- RELEASE=precise VERSION=master ALIAS=nightly

install:
- cp $HOME/.php-build/share/php-build/default_configure_options $HOME
- pushd $HOME/.php-build
- git checkout master
- git reset --hard origin/master
- git pull
- mv $HOME/default_configure_options $HOME/.php-build/share/php-build/default_configure_options
- popd
- sed -i -e '/xdebug/d' ~/.php-build/share/php-build/definitions/master
- sed -i -e 's/--without-pear/--with-pear/' ~/.php-build/share/php-build/default_configure_options

before_script:
- 'export LSB_RELEASE=${LSB_RELEASE:-$(lsb_release -rs || echo ${$(sw_vers -productVersion)%*.*})}'
- 'export OS_NAME=${OS_NAME:-$(lsb_release -is | tr "A-Z" "a-z" || echo "osx")}'
- 'export ARCH=${ARCH:-$(uname -m)}'
- 'export INSTALL_DEST=${INSTALL_DEST:-$HOME/.phpenv/versions}'
- __dots() { while true ; do echo -en . ; sleep 30 ; done } ; __dots &

script: ./bin/compile

after_success: ./bin/archive

after_failure: cat /tmp/php-build.*.log

addons:
  artifacts:
    paths:
    - $LSB_RELEASE/
    target_paths:
    - /binaries/$OS_NAME/$LSB_RELEASE/$ARCH
